# Generated by Django 3.0.8 on 2020-07-31 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outline',
            new_name='Blog',
        ),
    ]
