# Generated by Django 3.0.8 on 2020-08-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200731_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='specials/images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pageOne',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pageThree',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pageTwo',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
