# Generated by Django 3.0.8 on 2020-08-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200811_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='blog/images/'),
        ),
    ]
