# Generated by Django 3.0.8 on 2020-08-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200812_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pageFour',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pageFourImage',
            field=models.ImageField(default='SOME STRING', upload_to='blog/images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pageOneImage',
            field=models.ImageField(default='SOME STRING', upload_to='blog/images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pageThreeImage',
            field=models.ImageField(default='SOME STRING', upload_to='blog/images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pageTwoImage',
            field=models.ImageField(default='SOME STRING', upload_to='blog/images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='summaryImage',
            field=models.ImageField(default='SOME STRING', upload_to='blog/images/'),
        ),
    ]
