# Generated by Django 3.0.8 on 2020-08-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200812_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pageFour',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pageFourImage',
            field=models.ImageField(default='', upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pageOne',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pageOneImage',
            field=models.ImageField(default='', upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pageThree',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pageThreeImage',
            field=models.ImageField(default='', upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pageTwo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pageTwoImage',
            field=models.ImageField(default='', upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summaryImage',
            field=models.ImageField(default='', upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
