# Generated by Django 3.0.8 on 2020-08-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200812_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='by',
            field=models.CharField(default='', max_length=200),
        ),
    ]
